<template>
  <NucGridPage v-bind:gap="{'col':0,'row':0}" v-bind:rows="[1]"
    v-bind:schema="{'r0-c0':{'col':0,'row':0,'showIn':['xs','sm','md','lg'],'colSpan':1,'rowSpan':1}}"
    v-bind:columns="[1]" overflow="auto" v-bind:designMode="false" v-bind:minNsLimit="1050"
    v-bind:style="{'background':'#FFFFFF','paddingTop':'0px','paddingLeft':'0px','paddingRight':'0px','paddingBottom':'0px'}">
    <NucGridCell v-bind:wrap="true" v-bind:reverse="false" overflow="hidden" direction="column"
      v-bind:showInDevice="['xs','sm','md','lg']" verticalAlignment="top" horizontalAlignment="left"
      id="769712dc-8374-434b-a536-bbf44cf9d409" v-bind:col="0" v-bind:row="0" v-bind:colSpan="1" v-bind:rowSpan="1"
      v-bind:marginTop="0" v-bind:marginLeft="0" v-bind:marginRight="0" v-bind:marginBottom="0"
      v-bind:style="{'height':'auto','background':'transparent','paddingTop':'0px','borderColor':'','borderStyle':'solid','borderWidth':'0px','paddingLeft':'0px','borderRadius':'0px','paddingRight':'0px','paddingBottom':'0px','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'1px','borderTopRightRadius':'1px','borderBottomLeftRadius':'1px','borderBottomRightRadius':'1px'}"
      slot="r0-c0" area="r0-c0">
      <NucGroupElement top="0%" left="0%" v-bind:snapX="false" v-bind:snapY="false" v-bind:isLock="false" bgColor=""
        position="absolute" ncTooltipText="" id="dec44559-2a20-4c39-ad04-11e5e1646f2f"
        v-bind:style="{'color':'#FFFFFF','width':'1050px','height':'637.5px','zIndex':2,'fontSize':'8.44171875px','maxWidth':'','minWidth':'5.6278125','tabIndex':'-0.56278125','boxShadow':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'5.6278125','textAlign':'center','background':'','fontFamily':'Roboto-Regular,Roboto','fontWeight':'normal','lineHeight':'0.7034765625','marginLeft':'0px','paddingTop':'','textShadow':'','visibility':'visible','borderColor':'#767676','borderStyle':'solid','marginRight':'0px','paddingLeft':'','marginBottom':'0px','paddingRight':'','paddingBottom':'','borderTopWidth':'0.56278125px','textDecoration':'none','borderLeftWidth':'0.56278125px','borderRightWidth':'0.56278125px','borderBottomWidth':'0.56278125px','borderTopLeftRadius':'0px','borderTopRightRadius':'0px','borderBottomLeftRadius':'0px','borderBottomRightRadius':'0px'}">
        <WImage top="12.349117920148561%" left="0%" v-bind:blank="false" v-bind:snapX="false" v-bind:snapY="false"
          v-bind:rounded="false" stretch="none"
          imageUrl="https://c4.wallpaperflare.com/wallpaper/497/154/549/house-building-flowers-beautiful-wallpaper-preview.jpg"
          position="absolute" v-bind:isEnabled="true" v-bind:thumbnail="false" blankColor="black"
          v-bind:aspectRatio="true" dataLoading="static" ncTooltipText="Please write a text to display in tooltip..."
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':true,'structure':[{'type':'string','update':{'type':'dataModelForDynamicType'},'propName':'imageUrl','displayName':'Value'}]}"
          ncClickBorderColor="black" ncHoverBorderColor="black" dataModelForDynamicType="string"
          id="b4c00579-9070-4d09-aa53-ba657f08585e"
          v-bind:style="{'width':'525.6376875000001px','height':'442.90884374999996px','zIndex':4,'maxWidth':'','minWidth':'','boxShadow':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','borderColor':'#4B74FF','borderStyle':'solid','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'0px','borderTopRightRadius':'0px','borderBottomLeftRadius':'0px','borderBottomRightRadius':'0px'}"/>
        <WLabel top="16.15668402777778%" left="51.015625%" text="SELAM CANIM HOSGELDİN" v-bind:snapX="false"
          v-bind:snapY="false" theme="theme--light01" position="absolute" ncTypography="custom" ncTooltipText=""
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          id="47bc1efc-49a2-4cd1-b648-24dcf85ea8d3"
          v-bind:style="{'color':'#000000','width':'','height':'','zIndex':5,'fontSize':'25.32515625px','maxWidth':'','minWidth':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','fontFamily':'Roboto-Regular,Roboto','fontWeight':'normal','lineHeight':'0.78789375','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','textDecoration':'none'}"/>
        <WLabel top="24.882075471698112%" left="51.144492131616595%"
          text="Contact us for a quote. Help or to join the team" v-bind:snapX="false" v-bind:snapY="false"
          theme="theme--light01" position="absolute" ncTypography="custom" ncTooltipText=""
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          id="05599757-4b96-4d41-a171-3d0e181ac441"
          v-bind:style="{'color':'#000000','width':'262.5px','height':'15px','zIndex':6,'fontSize':'12.3811875px','maxWidth':'','minWidth':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','fontFamily':'Roboto-Regular,Roboto','fontWeight':'normal','lineHeight':'0.78789375','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','textDecoration':'none'}"/>
        <WIconButton tag="button" top="31.93069306930693%" icon="fab fa-twitter" left="50.83449235048679%"
          v-bind:pill="false" size="md" text="   " type="button" v-bind:block="false" color="#FFFFFF"
          v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="secondary"
          fontSize="" position="absolute" fontStyle="normal" iconColor="#000000" v-bind:isEnabled="true" minHeight=""
          background="#FFFFFF" fontFamily="OpenSans-Bold,Open Sans" fontWeight="400" layoutMode="left-to-right"
          lineHeight="1.2" textShadow="" borderColor="#6C757D" iconFontSize="35px" ncTypography="custom"
          iconAlignment="center" iconFontStyle="default" ncTooltipText="" verticalWidth="" iconFontFamily="font-awesome"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          textDecoration="none" verticalHeight="" horizontalWidth="" horizontalHeight="" ncClickFontColor="#FFFFFF"
          ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" verticalMinWidth="40px" verticalMinHeight="60px"
          horizontalMinWidth="96px" ncClickBorderColor="#4285f4" ncDisableFontColor="#FFFFFF"
          ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4" buttonTextAlignment="center"
          horizontalMinHeight="30px" ncDisableBorderColor="#4285f4" ncClickBackgroundColor="#4285f4"
          ncFocusBackgroundColor="#4285f4" ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#4285f4"
          id="66718d5b-ab05-4593-b9ce-b4f4fcaea4b3"
          v-bind:style="{'width':'37.518750000000004px','height':'27.0135px','zIndex':7,'maxWidth':'','minWidth':'8.44171875px','tabIndex':'0px','boxShadow':'','marginTop':'','maxHeight':'','marginLeft':'','paddingTop':'','visibility':'visible','borderStyle':'none','marginRight':'','paddingLeft':'','marginBottom':'','paddingRight':'','hasDesignMode':true,'paddingBottom':'','borderTopWidth':'0.56278125px','borderLeftWidth':'0.56278125px','borderRightWidth':'0.56278125px','borderBottomWidth':'0.56278125px','borderTopLeftRadius':'2.251125px','borderTopRightRadius':'2.251125px','borderBottomLeftRadius':'2.251125px','borderBottomRightRadius':'2.251125px'}"/>
        <WIconButton tag="button" top="31.93069306930693%" icon="fab fa-instagram" left="55.21557719054242%"
          v-bind:pill="false" size="md" text="   " type="button" v-bind:block="false" color="#FFFFFF"
          v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="secondary"
          fontSize="12px" position="absolute" fontStyle="normal" iconColor="#000000" v-bind:isEnabled="true"
          minHeight="" background="#FFFFFF" fontFamily="OpenSans-Bold,Open Sans" fontWeight="400"
          layoutMode="left-to-right" lineHeight="1.2" textShadow="" borderColor="#6C757D" iconFontSize="35px"
          ncTypography="custom" iconAlignment="center" iconFontStyle="default" ncTooltipText="" verticalWidth=""
          iconFontFamily="font-awesome"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          textDecoration="none" verticalHeight="" horizontalWidth="" horizontalHeight="" ncClickFontColor="#FFFFFF"
          ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" verticalMinWidth="40px" verticalMinHeight="60px"
          horizontalMinWidth="96px" ncClickBorderColor="#4285f4" ncDisableFontColor="#FFFFFF"
          ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4" buttonTextAlignment="center"
          horizontalMinHeight="30px" ncDisableBorderColor="#4285f4" ncClickBackgroundColor="#4285f4"
          ncFocusBackgroundColor="#4285f4" ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#4285f4"
          id="8722e517-552f-421f-b019-6be99a7d4899"
          v-bind:style="{'width':'34.517250000000004px','height':'27.0135px','zIndex':8,'maxWidth':'','minWidth':'8.44171875px','tabIndex':'0px','boxShadow':'','marginTop':'','maxHeight':'','marginLeft':'','paddingTop':'','visibility':'visible','borderStyle':'none','marginRight':'','paddingLeft':'','marginBottom':'','paddingRight':'','hasDesignMode':true,'paddingBottom':'','borderTopWidth':'0.56278125px','borderLeftWidth':'0.56278125px','borderRightWidth':'0.56278125px','borderBottomWidth':'0.56278125px','borderTopLeftRadius':'2.251125px','borderTopRightRadius':'2.251125px','borderBottomLeftRadius':'2.251125px','borderBottomRightRadius':'2.251125px'}"/>
        <WIconButton tag="button" top="31.524685936843714%" icon="fab fa-pinterest-p" left="59.585121602288986%"
          v-bind:pill="false" size="md" text="   " type="button" v-bind:block="false" color="#FFFFFF"
          v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="secondary"
          fontSize="12px" position="absolute" fontStyle="normal" iconColor="#000000" v-bind:isEnabled="true"
          minHeight="" background="#FFFFFF" fontFamily="OpenSans-Bold,Open Sans" fontWeight="400"
          layoutMode="left-to-right" lineHeight="1.2" textShadow="" borderColor="#6C757D" iconFontSize="35px"
          ncTypography="custom" iconAlignment="center" iconFontStyle="default" ncTooltipText="" verticalWidth=""
          iconFontFamily="font-awesome"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          textDecoration="none" verticalHeight="" horizontalWidth="" horizontalHeight="" ncClickFontColor="#FFFFFF"
          ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" verticalMinWidth="40px" verticalMinHeight="60px"
          horizontalMinWidth="96px" ncClickBorderColor="#4285f4" ncDisableFontColor="#FFFFFF"
          ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4" buttonTextAlignment="center"
          horizontalMinHeight="30px" ncDisableBorderColor="#4285f4" ncClickBackgroundColor="#4285f4"
          ncFocusBackgroundColor="#4285f4" ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#4285f4"
          id="c0b415be-5ddf-433b-9fb7-ab162817f0fd"
          v-bind:style="{'width':'31.5px','height':'27px','zIndex':9,'maxWidth':'','minWidth':'8.44171875px','tabIndex':'0px','boxShadow':'','marginTop':'','maxHeight':'','marginLeft':'','paddingTop':'','visibility':'visible','borderStyle':'none','marginRight':'','paddingLeft':'','marginBottom':'','paddingRight':'','hasDesignMode':true,'paddingBottom':'','borderTopWidth':'0.56278125px','borderLeftWidth':'0.56278125px','borderRightWidth':'0.56278125px','borderBottomWidth':'0.56278125px','borderTopLeftRadius':'2.251125px','borderTopRightRadius':'2.251125px','borderBottomLeftRadius':'2.251125px','borderBottomRightRadius':'2.251125px'}"/>
        <WIconButton tag="button" top="31.447834533196207%" icon="fas fa-basketball-ball" left="63.285714285714285%"
          v-bind:pill="false" size="md" text="   " type="button" v-bind:block="false" color="#FFFFFF"
          v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="secondary"
          fontSize="12px" position="absolute" fontStyle="normal" iconColor="#000000" v-bind:isEnabled="true"
          minHeight="" background="#FFFFFF" fontFamily="OpenSans-Bold,Open Sans" fontWeight="400"
          layoutMode="left-to-right" lineHeight="1.2" textShadow="" borderColor="#6C757D" iconFontSize="35px"
          ncTypography="custom" iconAlignment="center" iconFontStyle="default" ncTooltipText="" verticalWidth=""
          iconFontFamily="font-awesome"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          textDecoration="none" verticalHeight="" horizontalWidth="" horizontalHeight="" ncClickFontColor="#FFFFFF"
          ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" verticalMinWidth="40px" verticalMinHeight="60px"
          horizontalMinWidth="96px" ncClickBorderColor="#4285f4" ncDisableFontColor="#FFFFFF"
          ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4" buttonTextAlignment="center"
          horizontalMinHeight="30px" ncDisableBorderColor="#4285f4" ncClickBackgroundColor="#4285f4"
          ncFocusBackgroundColor="#4285f4" ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#4285f4"
          id="b74a0b04-7cdb-422d-b50f-ab5905d0e5e7"
          v-bind:style="{'width':'40.5px','height':'32.25px','zIndex':10,'maxWidth':'','minWidth':'8.44171875px','tabIndex':'0px','boxShadow':'','marginTop':'','maxHeight':'','marginLeft':'','paddingTop':'','visibility':'visible','borderStyle':'none','marginRight':'','paddingLeft':'','marginBottom':'','paddingRight':'','hasDesignMode':true,'paddingBottom':'','borderTopWidth':'0.56278125px','borderLeftWidth':'0.56278125px','borderRightWidth':'0.56278125px','borderBottomWidth':'0.56278125px','borderTopLeftRadius':'2.251125px','borderTopRightRadius':'2.251125px','borderBottomLeftRadius':'2.251125px','borderBottomRightRadius':'2.251125px'}"/>
        <WEmailInput id="17092ce4-e224-4563-816c-6946d80f5085" top="45.23003472222222%" v-bind:lazy="false"
          left="51.06689453125%" size="md" text="" v-bind:trim="false" v-bind:snapX="false" v-bind:snapY="false"
          v-bind:noWheel="false" v-bind:disabled="false" position="absolute" v-bind:readonly="false"
          v-bind:required="false" wordList="" v-bind:autofocus="false" v-bind:plaintext="false" background=""
          ariaInvalid="false" v-bind:debounceVal="0" ncInputType="email" placeholder="Enter a valid email address"
          v-bind:previewMode="true" autocomplete="" ncTypography="custom" v-bind:lazyFormatter="false" ncTooltipText=""
          v-bind:isWordListOpen="false"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':true,'structure':[{'type':'string','ncKey':'type','ncType':{'ncInputType':'number'},'ncValue':'number','propName':'text','displayName':'Value','nsDefaultValue':'string'}]}"
          v-bind:isNumberConvert="false" ncClickFontColor="#434855" ncFocusFontColor="#434855"
          ncHoverFontColor="#434855" ncMaxNumberValue="100" ncMinNumberValue="0" ncClickBorderColor="#000000"
          ncDisableFontColor="#434855" ncFocusBorderColor="#000000" ncHoverBorderColor="#000000"
          ncDisableBorderColor="#000000" formatterFunctionName="" ncClickBackgroundColor="#ffffff"
          ncFocusBackgroundColor="#ffffff" ncHoverBackgroundColor="#ffffff" ncDisableBackgroundColor="#ffffff"
          v-bind:style="{'color':'','width':'218.359125px','height':'36.58078125px','zIndex':11,'fontSize':'10.130062500000001px','maxWidth':'','minWidth':'88.9194375px','boxShadow':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','fontFamily':'Roboto-Regular,Roboto','fontWeight':'normal','lineHeight':'0.56278125','marginLeft':'0px','paddingTop':'0px','visibility':'visible','borderColor':'#D1D1D6','borderStyle':'solid','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','textDecoration':'none'}"/>
        <WSquaredSuccessButton tag="button" top="45.69444444444444%" left="73.515625%" v-bind:pill="false" size="md"
          text="Submit" type="button" v-bind:block="false" color="#000000" v-bind:snapX="false" v-bind:snapY="false"
          theme="theme--light01" v-bind:squared="true" variant="success" position="absolute" v-bind:isEnabled="true"
          background="#FFFFFF" borderColor="#030303" borderWidth="2px" ncTypography="custom" v-bind:resetTrigger="false"
          ncTooltipText="" verticalWidth="60px"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          verticalHeight="60px" horizontalWidth="72.4479px" horizontalHeight="37.5347px" ncClickFontColor="#FFFFFF"
          ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" ncClickBorderColor="#4285f4"
          ncDisableFontColor="#FFFFFF" ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4"
          ncDisableBorderColor="transparent" ncClickBackgroundColor="#4285f4" ncFocusBackgroundColor="#4285f4"
          ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#969696" id="1aabbcc8-0fdb-4441-86b1-0bfc54f82c5a"
          v-bind:style="{'width':'73.1615625px','height':'32.07853125px','zIndex':12,'fontSize':'11.255625px','maxWidth':'','minWidth':'','tabIndex':'0px','boxShadow':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'center','fontFamily':'OpenSans-Bold,Open Sans','fontWeight':'bold','lineHeight':'0.78789375','marginLeft':'0px','paddingTop':'','textShadow':'','visibility':'visible','borderStyle':'solid','marginRight':'0px','paddingLeft':'','marginBottom':'0px','paddingRight':'','paddingBottom':'','borderTopWidth':'1.1255625px','textDecoration':'none','borderLeftWidth':'1.1255625px','borderRightWidth':'1.1255625px','horizontalHeight':'21.123825384375px','borderBottomWidth':'1.1255625px','borderTopLeftRadius':'2.251125px','borderTopRightRadius':'2.251125px','borderBottomLeftRadius':'2.251125px','borderBottomRightRadius':'2.251125px'}"/>
        <WIconButton tag="button" top="61.705296116690214%" icon="fas fa-map-marker-alt" left="51.144492131616595%"
          v-bind:pill="false" size="md" text="   " type="button" v-bind:block="false" color="#FFFFFF"
          v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="secondary"
          fontSize="12px" position="absolute" fontStyle="normal" iconColor="#000000" v-bind:isEnabled="true"
          minHeight="" background="#FFFFFF" fontFamily="OpenSans-Bold,Open Sans" fontWeight="400"
          layoutMode="left-to-right" lineHeight="1.2" textShadow="" borderColor="#6C757D" iconFontSize="35px"
          ncTypography="custom" iconAlignment="center" iconFontStyle="default" ncTooltipText="" verticalWidth=""
          iconFontFamily="font-awesome"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          textDecoration="none" verticalHeight="" horizontalWidth="" horizontalHeight="" ncClickFontColor="#FFFFFF"
          ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" verticalMinWidth="40px" verticalMinHeight="60px"
          horizontalMinWidth="96px" ncClickBorderColor="#4285f4" ncDisableFontColor="#FFFFFF"
          ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4" buttonTextAlignment="center"
          horizontalMinHeight="30px" ncDisableBorderColor="#4285f4" ncClickBackgroundColor="#4285f4"
          ncFocusBackgroundColor="#4285f4" ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#4285f4"
          id="a05dd805-bfd5-41e9-976f-55cd76cdbcec"
          v-bind:style="{'width':'29.25px','height':'30.75px','zIndex':13,'maxWidth':'','minWidth':'8.44171875px','tabIndex':'0px','boxShadow':'','marginTop':'','maxHeight':'','marginLeft':'','paddingTop':'','visibility':'visible','borderStyle':'none','marginRight':'','paddingLeft':'','marginBottom':'','paddingRight':'','hasDesignMode':true,'paddingBottom':'','borderTopWidth':'0.56278125px','borderLeftWidth':'0.56278125px','borderRightWidth':'0.56278125px','borderBottomWidth':'0.56278125px','borderTopLeftRadius':'2.251125px','borderTopRightRadius':'2.251125px','borderBottomLeftRadius':'2.251125px','borderBottomRightRadius':'2.251125px'}"/>
        <WIconButton tag="button" top="61.712239583333336%" icon="fas fa-mobile-alt" left="77.213134765625%"
          v-bind:pill="false" size="md" text="   " type="button" v-bind:block="false" color="#FFFFFF"
          v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="secondary"
          fontSize="12px" position="absolute" fontStyle="normal" iconColor="#000000" v-bind:isEnabled="true"
          minHeight="" background="#FFFFFF" fontFamily="OpenSans-Bold,Open Sans" fontWeight="400"
          layoutMode="left-to-right" lineHeight="1.2" textShadow="" borderColor="#6C757D" iconFontSize="35px"
          ncTypography="custom" iconAlignment="center" iconFontStyle="default" ncTooltipText="" verticalWidth=""
          iconFontFamily="font-awesome"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          textDecoration="none" verticalHeight="" horizontalWidth="" horizontalHeight="" ncClickFontColor="#FFFFFF"
          ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" verticalMinWidth="40px" verticalMinHeight="60px"
          horizontalMinWidth="96px" ncClickBorderColor="#4285f4" ncDisableFontColor="#FFFFFF"
          ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4" buttonTextAlignment="center"
          horizontalMinHeight="30px" ncDisableBorderColor="#4285f4" ncClickBackgroundColor="#4285f4"
          ncFocusBackgroundColor="#4285f4" ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#4285f4"
          id="d5c4f497-2ae7-4aad-b504-e0e42b3aec03"
          v-bind:style="{'width':'26.45071875px','height':'30.390187500000003px','zIndex':14,'maxWidth':'','minWidth':'8.44171875px','tabIndex':'0px','boxShadow':'','marginTop':'','maxHeight':'','marginLeft':'','paddingTop':'','visibility':'visible','borderStyle':'none','marginRight':'','paddingLeft':'','marginBottom':'','paddingRight':'','hasDesignMode':true,'paddingBottom':'','borderTopWidth':'0.56278125px','borderLeftWidth':'0.56278125px','borderRightWidth':'0.56278125px','borderBottomWidth':'0.56278125px','borderTopLeftRadius':'2.251125px','borderTopRightRadius':'2.251125px','borderBottomLeftRadius':'2.251125px','borderBottomRightRadius':'2.251125px'}"/>
        <WLabel top="68.65668402777777%" left="51.84814453125%" text="Address" v-bind:snapX="false" v-bind:snapY="false"
          theme="theme--light01" position="absolute" ncTypography="custom" ncTooltipText=""
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          id="664a9b45-4bc3-4b4b-921a-5ba2b46007d5"
          v-bind:style="{'color':'#000000','width':'','height':'','zIndex':15,'fontSize':'14.06953125px','maxWidth':'','minWidth':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','fontFamily':'OpenSans-SemiBold,Open Sans','fontWeight':'normal','lineHeight':'0.78789375','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','textDecoration':'none'}"/>
        <WLabel top="68.84114583333333%" left="77.62939453125%" text="Phone" v-bind:snapX="false" v-bind:snapY="false"
          theme="theme--light01" position="absolute" ncTypography="custom" ncTooltipText=""
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          id="00ad4bf4-b14f-40f6-8b43-41d6550ec735"
          v-bind:style="{'color':'#000000','width':'','height':'','zIndex':16,'fontSize':'14.06953125px','maxWidth':'','minWidth':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','fontFamily':'OpenSans-SemiBold,Open Sans','fontWeight':'normal','lineHeight':'0.78789375','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','textDecoration':'none'}"/>
        <WLabel top="73.82075471698113%" left="51.93133047210301%" text="Sample text. Click to select the text box"
          v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" position="absolute" ncTypography="custom"
          ncTooltipText=""
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          id="c67671a4-f6de-4ce3-9386-6ded911ece72"
          v-bind:style="{'color':'#747474','width':'180px','height':'25.5px','zIndex':17,'fontSize':'11.255625px','maxWidth':'','minWidth':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','fontFamily':'Roboto-Regular,Roboto','fontWeight':'normal','lineHeight':'0.78789375','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','textDecoration':'none'}"/>
        <WLabel top="73.76470588235294%" left="77.57142857142857%" text="Sample text. Click to select the text box"
          v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" position="absolute" ncTypography="custom"
          ncTooltipText=""
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          id="79215296-e897-4b7b-b3bf-6ddf2dc30671"
          v-bind:style="{'color':'#747474','width':'180px','height':'25.5px','zIndex':18,'fontSize':'11.255625px','maxWidth':'','minWidth':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','fontFamily':'Roboto-Regular,Roboto','fontWeight':'normal','lineHeight':'0.78789375','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','textDecoration':'none'}"/>
      </NucGroupElement>
    </NucGridCell>
  </NucGridPage>
</template>
<script>
export default {
  name: 'Screen1',
  data() {
    return {};
  },
  props: {},
  created() {},
  mounted() {},
  computed: {},
  methods: {},
  watch: {},
};
</script>

<style scoped></style>